pid: 0x1000
pver: 0xb3
vstr: Unipart Digital
pstr: Pi Tail
pins:
  8:
    function: alt0
  9:
    function: alt0
  10:
    function: alt0
  11:
    function: alt0
  23:
    function: input
    pull: none
  24:
    function: input
    pull: none
  25:
    function: input
    pull: down
